### ISSUE TITLE
ERROR `/css/main.css' not found.

### ISSUE THREAD

**Issue by rchatham** [taniarascia/startjekyll#4]
Awesome tutorial! Definitely a huge help in building sites in jeykll.

I have been getting the following error running this with the latest version of jekyll:
```
ERROR `/css/main.css' not found.
```
Any help would be appreciated.

**Comment by jvkrakowski** [comment]
If this is where you're importing your sass, then you need to go to your _sass folder and make sure the names of your files have an underscore underneath. Also, make sure you're calling the main.css correctly: 

`<link rel="stylesheet" href={{ "/css/style.css" | prepend: site.url }}>`
